let essentialOils = [
    {name: "Lavendar", quantity: 0, price: 2},
    {name: "Tea Tree", quantity: 0, price: 2},
    {name: "Lemon Grass", quantity: 0, price: 2},
    {name: "Rosehip", quantity: 0, price: 2},
    {name: "Chamomile", quantity: 0, price: 2},
    {name: "Sandalwood", quantity: 0, price: 2},
    {name: "Clary Sage", quantity: 0, price: 2},
    {name: "Rosemary", quantity: 0, price: 2},
    {name: "Frankincense", quantity: 0, price: 2},
    {name: "Geranium", quantity: 0, price: 2},
    {name: "Neroli", quantity: 0, price: 2},
    {name: "Lemon", quantity: 0, price: 2},
    {name: "Cinnamon", quantity: 0, price: 2},
    {name: "Peppermint", quantity: 0, price: 2},
    {name: "Wintergreen", quantity: 0, price: 2},
    {name: "Eucalyptus", quantity: 0, price: 2},
    {name: "Patchouli", quantity: 0, price: 2},
    {name: "Pomegranate", quantity: 0, price: 2},
    {name: "Carrot Seed", quantity: 0, price: 2},
    {name: "Tangerine", quantity: 0, price: 2},
    {name: "Ylang ylang", quantity: 0, price: 2},
    {name: "Rose", quantity: 0, price: 2},
    {name: "Myrrh", quantity: 0, price: 2},
    {name: "Jojoba", quantity: 0, price: 2},
];