export let essentialOils = [
    {name: "Lavendar", quantity: 0, price: 2},
    {name: "Tea Tree", quantity: 0, price: 2},
    {name: "Lemon Grass", quantity: 0, price: 2},
    {name: "Rosehip", quantity: 0, price: 2},
    {name: "Chamomile", quantity: 0, price: 2},
    {name: "Sandalwood", quantity: 0, price: 2},
    {name: "Clary Sage", quantity: 0, price: 2},
    {name: "Rosemary", quantity: 0, price: 2},
    {name: "Frankincense", quantity: 0, price: 2},
    {name: "Geranium", quantity: 0, price: 2},
    {name: "Neroli", quantity: 0, price: 2},
    {name: "Lemon", quantity: 0, price: 2},
    {name: "Cinnamon", quantity: 0, price: 2},
    {name: "Peppermint", quantity: 0, price: 2},
    {name: "Wintergreen", quantity: 0, price: 2},
    {name: "Eucalyptus", quantity: 0, price: 2},
    {name: "Patchouli", quantity: 0, price: 2},
    {name: "Pomegranate", quantity: 0, price: 2},
    {name: "Carrot Seed", quantity: 0, price: 2},
    {name: "Tangerine", quantity: 0, price: 2},
    {name: "Ylang ylang", quantity: 0, price: 2},
    {name: "Rose", quantity: 0, price: 2},
    {name: "Myrrh", quantity: 0, price: 2},
    {name: "Jojoba", quantity: 0, price: 2},
]

export const carrierOils = [
    {name: "Almond", quantity: 0, price: 3},
    {name: "Apricot Kernel", quantity: 0, price: 3},
    {name: "Argan", quantity: 0, price: 3},
    {name: "Avocado", quantity: 0, price: 3},
    {name: "Black Seed", quantity: 0, price: 3},
    {name: "Camellia Seed", quantity: 0, price: 3},
    {name: "Coconut", quantity: 0, price: 3},
    {name: "Cucumber Seed", quantity: 0, price: 3},
    {name: "Evening Primrose", quantity: 0, price: 3},
    {name: "Grape Seed", quantity: 0, price: 3},
    {name: "Guava Seed", quantity: 0, price: 3},
    {name: "Hemp Seed", quantity: 0, price: 3},
    {name: "Jojoba", quantity: 0, price: 3},
    {name: "Macadamia", quantity: 0, price: 3},
    {name: "Olive", quantity: 0, price: 3},
    {name: "Rosehip", quantity: 0, price: 3},
    {name: "Sunflower", quantity: 0, price: 3},
    {name: "Wheat Germ", quantity: 0, price: 3},
    {name: "Shea Butter", quantity: 0, price: 4},
]

export const addins = [
    {name: "Coffee Grounds", quantity: 0, price: 4},
    {name: "Sea Salt", quantity: 0, price: 4},
    {name: "Sugar", quantity: 0, price: 4},
    {name: "Oatmeal", quantity: 0, price: 4},
    {name: "Flaxseeds", quantity: 0, price: 4},
    {name: "Vitamin E", quantity: 0, price: 4},
    {name: "Baking Soda", quantity: 0, price: 4},
    {name: "Rice", quantity: 0, price: 4},
    {name: "Charcoal", quantity: 0, price: 4},
    {name: "Matcha", quantity: 0, price: 4},
    {name: "Biotin", quantity: 0, price: 4},
]

